image: Visual Studio 2019
configuration:
 - Release

platform:
 - x64

install:
 - qmake
 - make

build:
  project: x64\VS2019\opus-tools.sln
  parallel: false
  verbosity: minimal

artifacts:
 - path: AmongUsDecentralized
