os: unstable
skip_tags: true

install:
- set QTDIR=C:\Qt\5.5\mingw492_32
- set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
- set RELEASE_PATH=appveyor\release

build_script:
- copy appveyor\qopenglversionfunctions.h %QTDIR%\include\QtGui
- sed -i s/_hypot/hypot/g c:\mingw\include\math.h
- sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" AmongUsDecentralized.pro
- qmake AmongUsDecentralized.pro -r -spec win32-g++
- mingw32-make
