skip_tags: true

branches:
  only:
    - master

environment:
  global:
    qtdir5152: C:\Qt\5.15.2\mingw81_32
    qtdirlatest: C:\Qt\latest\mingw81_32
    CCACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\.ccache"

  matrix:
    - QTDIR: C:\Qt\5.15.2\mingw81_32
      TOOLCHAIN_VERSION: 810_32
      gpp: win32-g++

install:
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;C:\Qt\Tools\mingw%TOOLCHAIN_VERSION%\bin
  - set RELEASE_PATH=appveyor\release
  - set TEST_PATH=appveyor\test
  - powershell "$file = 'AmongUsDecentralized.pro'; $content = Get-Content $file; $content[0..($content.length-20)]|Out-File $file -Encoding ascii"
  
build_script:
  - sed -i "s/CONFIG += c++11/QMAKE_CXXFLAGS += -std=gnu++0x/g" AmongUsDecentralized.pro
  - qmake AmongUsDecentralized.pro -r -spec %gpp% CONFIG+=ccache
  - mingw32-make
