install:
  - set PATH=%PATH%;C:\Qt\Tools\mingw810_32\bin
  - powershell "$file = 'AmongUsDecentralized.pro'; $content = Get-Content $file; $content[0..($content.length-20)]|Out-File $file -Encoding ascii"
  
build_script:
  - qmake AmongUsDecentralized.pro
  - mingw32-make

artifacts:
  - path: release/AmongUsDecentralized.exe
