image: Ubuntu2004
configuration:
 - Release

platform:
 - x64

install:
 - sudo apt install -y libgl-dev

build_script:
 - $HOME/Qt/5.15.2/gcc_64/bin/qmake
 - make

artifacts:
 - path: AmongUsDecentralized
