install:
  - set PATH=%PATH%;C:\Qt\5.15.2\mingw81_64\bin;C:\Qt\Tools\mingw810_64\bin
  - powershell "$file = 'AmongUsDecentralized.pro'; $content = Get-Content $file; $content[0..($content.length-12)]|Out-File $file -Encoding ascii"
  
build_script:
  - qmake AmongUsDecentralized.pro
  - mingw32-make

artifacts:
  - path: release/AmongUsDecentralized.exe
