image: Visual Studio 2017
configuration:
 - Release

platform:
 - x64

install:
 - set QTDIR=C:\Qt\5.13.2\mingw73_64
 - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\mingw730_32\bin
build_script:
 - qmake
 - mingw32-make

artifacts:
 - path: AmongUsDecentralized
