image: Visual Studio 2019
configuration:
 - Release

platform:
 - x64

install:
 - C:\Qt\6.2.0\mingw81_64\bin\qmake.exe
 - make

build:
  project: x64\VS2019\opus-tools.sln
  parallel: false
  verbosity: minimal

artifacts:
 - path: AmongUsDecentralized
