language: cpp
dist: focal
compiler: g++
sudo: required

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-focal -y
 - sudo apt update
install:
 - sudo apt install qt515base qt515multimedia libgl-dev moreutils
 - source /opt/qt515/bin/qt515-env.sh
 - head -n -19 AmongUsDecentralized.pro | sponge AmongUsDecentralized.pro
script:
 - /opt/qt515/bin/qmake PREFIX=/usr
 - make
