name: Mac
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - run: brew install qt5
    - run: echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile
    - run: export LDFLAGS="-L/usr/local/opt/qt@5/lib"
    - run: export CPPFLAGS="-I/usr/local/opt/qt@5/include"
    - run: export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
    - run: /usr/local/opt/qt@5/bin/qmake
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: AmongUsDecentralized
        path: AmongUsDecentralized.app/Contents/MacOS/AmongUsDecentralized
